return {
  "williamboman/mason.nvim",
  cmd = "Mason",
  keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "black",
      "clang-format",
      "css-lsp",
      "dockerfile-language-server",
      "eslint_d",
      "eslint-lsp",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "php-cs-fixer",
      "prettierd",
      "python-lsp-server",
      "rust-analyzer",
      "shellcheck",
      "shellharden",
      "shfmt",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "terraform-ls",
      "tflint",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
